language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install ."
  - "pip install -r test-requirements.txt"
script:
  - "flake8 ."
  - "memcached -U 11211 &"
  - "memcached -U 11212 &"
  - "nosetests"
